<?php
/**
 * PermissionMailboxControllerApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DocStudio Api Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: R74.25
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.41
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Docstudio\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * PermissionMailboxControllerApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PermissionMailboxControllerApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation deleteAllPermissions
     *
     * Delete all permissions and roles for selected user-to-mailbox relation
     *
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteAllPermissions($user_uuid, $mailbox_uuid)
    {
        $this->deleteAllPermissionsWithHttpInfo($user_uuid, $mailbox_uuid);
    }

    /**
     * Operation deleteAllPermissionsWithHttpInfo
     *
     * Delete all permissions and roles for selected user-to-mailbox relation
     *
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteAllPermissionsWithHttpInfo($user_uuid, $mailbox_uuid)
    {
        $returnType = '';
        $request = $this->deleteAllPermissionsRequest($user_uuid, $mailbox_uuid);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation deleteAllPermissionsAsync
     *
     * Delete all permissions and roles for selected user-to-mailbox relation
     *
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAllPermissionsAsync($user_uuid, $mailbox_uuid)
    {
        return $this->deleteAllPermissionsAsyncWithHttpInfo($user_uuid, $mailbox_uuid)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteAllPermissionsAsyncWithHttpInfo
     *
     * Delete all permissions and roles for selected user-to-mailbox relation
     *
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAllPermissionsAsyncWithHttpInfo($user_uuid, $mailbox_uuid)
    {
        $returnType = '';
        $request = $this->deleteAllPermissionsRequest($user_uuid, $mailbox_uuid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteAllPermissions'
     *
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deleteAllPermissionsRequest($user_uuid, $mailbox_uuid)
    {
        // verify the required parameter 'user_uuid' is set
        if ($user_uuid === null || (is_array($user_uuid) && count($user_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $user_uuid when calling deleteAllPermissions'
            );
        }
        // verify the required parameter 'mailbox_uuid' is set
        if ($mailbox_uuid === null || (is_array($mailbox_uuid) && count($mailbox_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $mailbox_uuid when calling deleteAllPermissions'
            );
        }

        $resourcePath = '/api/v1/permission/{userUuid}/mailbox/{mailboxUuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($user_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'userUuid' . '}',
                ObjectSerializer::toPathValue($user_uuid),
                $resourcePath
            );
        }
        // path params
        if ($mailbox_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'mailboxUuid' . '}',
                ObjectSerializer::toPathValue($mailbox_uuid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deletePermission
     *
     * Delete permission for specific user-to-mailbox relation
     *
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     * @param  int $permission_id Permission Id (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deletePermission($user_uuid, $mailbox_uuid, $permission_id)
    {
        $this->deletePermissionWithHttpInfo($user_uuid, $mailbox_uuid, $permission_id);
    }

    /**
     * Operation deletePermissionWithHttpInfo
     *
     * Delete permission for specific user-to-mailbox relation
     *
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     * @param  int $permission_id Permission Id (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deletePermissionWithHttpInfo($user_uuid, $mailbox_uuid, $permission_id)
    {
        $returnType = '';
        $request = $this->deletePermissionRequest($user_uuid, $mailbox_uuid, $permission_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation deletePermissionAsync
     *
     * Delete permission for specific user-to-mailbox relation
     *
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     * @param  int $permission_id Permission Id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deletePermissionAsync($user_uuid, $mailbox_uuid, $permission_id)
    {
        return $this->deletePermissionAsyncWithHttpInfo($user_uuid, $mailbox_uuid, $permission_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deletePermissionAsyncWithHttpInfo
     *
     * Delete permission for specific user-to-mailbox relation
     *
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     * @param  int $permission_id Permission Id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deletePermissionAsyncWithHttpInfo($user_uuid, $mailbox_uuid, $permission_id)
    {
        $returnType = '';
        $request = $this->deletePermissionRequest($user_uuid, $mailbox_uuid, $permission_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deletePermission'
     *
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     * @param  int $permission_id Permission Id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deletePermissionRequest($user_uuid, $mailbox_uuid, $permission_id)
    {
        // verify the required parameter 'user_uuid' is set
        if ($user_uuid === null || (is_array($user_uuid) && count($user_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $user_uuid when calling deletePermission'
            );
        }
        // verify the required parameter 'mailbox_uuid' is set
        if ($mailbox_uuid === null || (is_array($mailbox_uuid) && count($mailbox_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $mailbox_uuid when calling deletePermission'
            );
        }
        // verify the required parameter 'permission_id' is set
        if ($permission_id === null || (is_array($permission_id) && count($permission_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $permission_id when calling deletePermission'
            );
        }

        $resourcePath = '/api/v1/permission/{userUuid}/mailbox/{mailboxUuid}/{permissionId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($user_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'userUuid' . '}',
                ObjectSerializer::toPathValue($user_uuid),
                $resourcePath
            );
        }
        // path params
        if ($mailbox_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'mailboxUuid' . '}',
                ObjectSerializer::toPathValue($mailbox_uuid),
                $resourcePath
            );
        }
        // path params
        if ($permission_id !== null) {
            $resourcePath = str_replace(
                '{' . 'permissionId' . '}',
                ObjectSerializer::toPathValue($permission_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteRoleFromMailbox
     *
     * Delete role
     *
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     * @param  string $role_uuid UUID of role (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteRoleFromMailbox($user_uuid, $mailbox_uuid, $role_uuid)
    {
        $this->deleteRoleFromMailboxWithHttpInfo($user_uuid, $mailbox_uuid, $role_uuid);
    }

    /**
     * Operation deleteRoleFromMailboxWithHttpInfo
     *
     * Delete role
     *
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     * @param  string $role_uuid UUID of role (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteRoleFromMailboxWithHttpInfo($user_uuid, $mailbox_uuid, $role_uuid)
    {
        $returnType = '';
        $request = $this->deleteRoleFromMailboxRequest($user_uuid, $mailbox_uuid, $role_uuid);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation deleteRoleFromMailboxAsync
     *
     * Delete role
     *
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     * @param  string $role_uuid UUID of role (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteRoleFromMailboxAsync($user_uuid, $mailbox_uuid, $role_uuid)
    {
        return $this->deleteRoleFromMailboxAsyncWithHttpInfo($user_uuid, $mailbox_uuid, $role_uuid)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteRoleFromMailboxAsyncWithHttpInfo
     *
     * Delete role
     *
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     * @param  string $role_uuid UUID of role (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteRoleFromMailboxAsyncWithHttpInfo($user_uuid, $mailbox_uuid, $role_uuid)
    {
        $returnType = '';
        $request = $this->deleteRoleFromMailboxRequest($user_uuid, $mailbox_uuid, $role_uuid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteRoleFromMailbox'
     *
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     * @param  string $role_uuid UUID of role (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deleteRoleFromMailboxRequest($user_uuid, $mailbox_uuid, $role_uuid)
    {
        // verify the required parameter 'user_uuid' is set
        if ($user_uuid === null || (is_array($user_uuid) && count($user_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $user_uuid when calling deleteRoleFromMailbox'
            );
        }
        // verify the required parameter 'mailbox_uuid' is set
        if ($mailbox_uuid === null || (is_array($mailbox_uuid) && count($mailbox_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $mailbox_uuid when calling deleteRoleFromMailbox'
            );
        }
        // verify the required parameter 'role_uuid' is set
        if ($role_uuid === null || (is_array($role_uuid) && count($role_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $role_uuid when calling deleteRoleFromMailbox'
            );
        }

        $resourcePath = '/api/v1/permission/{userUuid}/mailbox/{mailboxUuid}/role/{roleUuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($user_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'userUuid' . '}',
                ObjectSerializer::toPathValue($user_uuid),
                $resourcePath
            );
        }
        // path params
        if ($mailbox_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'mailboxUuid' . '}',
                ObjectSerializer::toPathValue($mailbox_uuid),
                $resourcePath
            );
        }
        // path params
        if ($role_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'roleUuid' . '}',
                ObjectSerializer::toPathValue($role_uuid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation patchMbPermissions
     *
     * Add exact permissions/roles leaving existing as is. Ignore if already present.
     *
     * @param  \Swagger\Client\Model\PermissionsDTO $body body (required)
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function patchMbPermissions($body, $user_uuid, $mailbox_uuid)
    {
        $this->patchMbPermissionsWithHttpInfo($body, $user_uuid, $mailbox_uuid);
    }

    /**
     * Operation patchMbPermissionsWithHttpInfo
     *
     * Add exact permissions/roles leaving existing as is. Ignore if already present.
     *
     * @param  \Swagger\Client\Model\PermissionsDTO $body (required)
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function patchMbPermissionsWithHttpInfo($body, $user_uuid, $mailbox_uuid)
    {
        $returnType = '';
        $request = $this->patchMbPermissionsRequest($body, $user_uuid, $mailbox_uuid);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation patchMbPermissionsAsync
     *
     * Add exact permissions/roles leaving existing as is. Ignore if already present.
     *
     * @param  \Swagger\Client\Model\PermissionsDTO $body (required)
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchMbPermissionsAsync($body, $user_uuid, $mailbox_uuid)
    {
        return $this->patchMbPermissionsAsyncWithHttpInfo($body, $user_uuid, $mailbox_uuid)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation patchMbPermissionsAsyncWithHttpInfo
     *
     * Add exact permissions/roles leaving existing as is. Ignore if already present.
     *
     * @param  \Swagger\Client\Model\PermissionsDTO $body (required)
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchMbPermissionsAsyncWithHttpInfo($body, $user_uuid, $mailbox_uuid)
    {
        $returnType = '';
        $request = $this->patchMbPermissionsRequest($body, $user_uuid, $mailbox_uuid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'patchMbPermissions'
     *
     * @param  \Swagger\Client\Model\PermissionsDTO $body (required)
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function patchMbPermissionsRequest($body, $user_uuid, $mailbox_uuid)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling patchMbPermissions'
            );
        }
        // verify the required parameter 'user_uuid' is set
        if ($user_uuid === null || (is_array($user_uuid) && count($user_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $user_uuid when calling patchMbPermissions'
            );
        }
        // verify the required parameter 'mailbox_uuid' is set
        if ($mailbox_uuid === null || (is_array($mailbox_uuid) && count($mailbox_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $mailbox_uuid when calling patchMbPermissions'
            );
        }

        $resourcePath = '/api/v1/permission/{userUuid}/mailbox/{mailboxUuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($user_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'userUuid' . '}',
                ObjectSerializer::toPathValue($user_uuid),
                $resourcePath
            );
        }
        // path params
        if ($mailbox_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'mailboxUuid' . '}',
                ObjectSerializer::toPathValue($mailbox_uuid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation replaceAllPermissions
     *
     * Replace all permissions for selected user-to-mailbox relation
     *
     * @param  \Swagger\Client\Model\PermissionsDTO $body body (required)
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function replaceAllPermissions($body, $user_uuid, $mailbox_uuid)
    {
        $this->replaceAllPermissionsWithHttpInfo($body, $user_uuid, $mailbox_uuid);
    }

    /**
     * Operation replaceAllPermissionsWithHttpInfo
     *
     * Replace all permissions for selected user-to-mailbox relation
     *
     * @param  \Swagger\Client\Model\PermissionsDTO $body (required)
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function replaceAllPermissionsWithHttpInfo($body, $user_uuid, $mailbox_uuid)
    {
        $returnType = '';
        $request = $this->replaceAllPermissionsRequest($body, $user_uuid, $mailbox_uuid);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation replaceAllPermissionsAsync
     *
     * Replace all permissions for selected user-to-mailbox relation
     *
     * @param  \Swagger\Client\Model\PermissionsDTO $body (required)
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function replaceAllPermissionsAsync($body, $user_uuid, $mailbox_uuid)
    {
        return $this->replaceAllPermissionsAsyncWithHttpInfo($body, $user_uuid, $mailbox_uuid)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation replaceAllPermissionsAsyncWithHttpInfo
     *
     * Replace all permissions for selected user-to-mailbox relation
     *
     * @param  \Swagger\Client\Model\PermissionsDTO $body (required)
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function replaceAllPermissionsAsyncWithHttpInfo($body, $user_uuid, $mailbox_uuid)
    {
        $returnType = '';
        $request = $this->replaceAllPermissionsRequest($body, $user_uuid, $mailbox_uuid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'replaceAllPermissions'
     *
     * @param  \Swagger\Client\Model\PermissionsDTO $body (required)
     * @param  string $user_uuid UUID of User (required)
     * @param  string $mailbox_uuid UUID of mailbox (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function replaceAllPermissionsRequest($body, $user_uuid, $mailbox_uuid)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling replaceAllPermissions'
            );
        }
        // verify the required parameter 'user_uuid' is set
        if ($user_uuid === null || (is_array($user_uuid) && count($user_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $user_uuid when calling replaceAllPermissions'
            );
        }
        // verify the required parameter 'mailbox_uuid' is set
        if ($mailbox_uuid === null || (is_array($mailbox_uuid) && count($mailbox_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $mailbox_uuid when calling replaceAllPermissions'
            );
        }

        $resourcePath = '/api/v1/permission/{userUuid}/mailbox/{mailboxUuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($user_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'userUuid' . '}',
                ObjectSerializer::toPathValue($user_uuid),
                $resourcePath
            );
        }
        // path params
        if ($mailbox_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'mailboxUuid' . '}',
                ObjectSerializer::toPathValue($mailbox_uuid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
