<?php
/**
 * ActivityLogObjectType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DocStudio\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DocStudio Api Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: R125.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DocStudio\Client\Model;
use \DocStudio\Client\ObjectSerializer;

/**
 * ActivityLogObjectType Class Doc Comment
 *
 * @category Class
 * @description Object type
 * @package  DocStudio\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ActivityLogObjectType
{
    /**
     * Possible values of this enum
     */
    public const TEMPLATE = 'template';

    public const ENVELOPE = 'envelope';

    public const DICTIONARY = 'dictionary';

    public const MAILBOX = 'mailbox';

    public const MAILBOX_ALIAS = 'mailbox_alias';

    public const CATEGORY = 'category';

    public const MAILBOX_FILTER = 'mailbox_filter';

    public const MAILBOX_LABEL = 'mailbox_label';

    public const USER = 'user';

    public const ACCOUNT = 'account';

    public const SCENARIO = 'scenario';

    public const ACCOUNT_DOMAIN = 'account_domain';

    public const ROLE = 'role';

    public const INTEGRATION_RULE = 'integration_rule';

    public const CRYPTO_CONFIG = 'crypto_config';

    public const EXTERNAL_LINK = 'external_link';

    public const APPROVAL_FLOW = 'approval_flow';

    public const ACCOUNT_TARIFF = 'account_tariff';

    public const ACCOUNT_SSO_ID_PROVIDER = 'account_sso_id_provider';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::TEMPLATE,
            self::ENVELOPE,
            self::DICTIONARY,
            self::MAILBOX,
            self::MAILBOX_ALIAS,
            self::CATEGORY,
            self::MAILBOX_FILTER,
            self::MAILBOX_LABEL,
            self::USER,
            self::ACCOUNT,
            self::SCENARIO,
            self::ACCOUNT_DOMAIN,
            self::ROLE,
            self::INTEGRATION_RULE,
            self::CRYPTO_CONFIG,
            self::EXTERNAL_LINK,
            self::APPROVAL_FLOW,
            self::ACCOUNT_TARIFF,
            self::ACCOUNT_SSO_ID_PROVIDER
        ];
    }
}


