<?php
/**
 * DocumentsForSignRequestDTOTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DocStudio\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DocStudio Api Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: R110.5
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace DocStudio\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DocumentsForSignRequestDTOTest Class Doc Comment
 *
 * @category    Class
 * @description DocumentsForSignRequestDTO
 * @package     DocStudio\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DocumentsForSignRequestDTOTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DocumentsForSignRequestDTO"
     */
    public function testDocumentsForSignRequestDTO()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "signing_certificate"
     */
    public function testPropertySigningCertificate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "skip_binary_files"
     */
    public function testPropertySkipBinaryFiles()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "documents"
     */
    public function testPropertyDocuments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
