<?php
/**
 * IntegrationRuleRequestDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Docstudio\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DocStudio Api Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: R74.25
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.41
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Docstudio\Client;

/**
 * IntegrationRuleRequestDTOTest Class Doc Comment
 *
 * @category    Class
 * @description Request details
 * @package     Docstudio\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IntegrationRuleRequestDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IntegrationRuleRequestDTO"
     */
    public function testIntegrationRuleRequestDTO()
    {
    }

    /**
     * Test attribute "mailbox_uuid"
     */
    public function testPropertyMailboxUuid()
    {
    }

    /**
     * Test attribute "template_uuid"
     */
    public function testPropertyTemplateUuid()
    {
    }

    /**
     * Test attribute "version_uuid"
     */
    public function testPropertyVersionUuid()
    {
    }

    /**
     * Test attribute "in"
     */
    public function testPropertyIn()
    {
    }

    /**
     * Test attribute "naming_rule"
     */
    public function testPropertyNamingRule()
    {
    }

    /**
     * Test attribute "map"
     */
    public function testPropertyMap()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }
}
