<?php
/**
 * SessionPolicyTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DocStudio\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DocStudio Api Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: R110.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace DocStudio\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SessionPolicyTest Class Doc Comment
 *
 * @category    Class
 * @description Session policy
 * @package     DocStudio\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SessionPolicyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SessionPolicy"
     */
    public function testSessionPolicy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "session_hours"
     */
    public function testPropertySessionHours()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "single_session"
     */
    public function testPropertySingleSession()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "single_ip_session"
     */
    public function testPropertySingleIpSession()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "max_login_attempts"
     */
    public function testPropertyMaxLoginAttempts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "max_attempts_timeout_minutes"
     */
    public function testPropertyMaxAttemptsTimeoutMinutes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "allowed_ips"
     */
    public function testPropertyAllowedIps()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "blocked_ips"
     */
    public function testPropertyBlockedIps()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
