<?php
/**
 * ExternalLinkControllerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DocStudio Api Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: R74.25
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.41
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Docstudio\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ExternalLinkControllerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ExternalLinkControllerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createExternalLink
     *
     * Create external link.
     *
     */
    public function testCreateExternalLink()
    {
    }

    /**
     * Test case for deleteExternalLink
     *
     * Delete external link.
     *
     */
    public function testDeleteExternalLink()
    {
    }

    /**
     * Test case for getAccountExternalLinks
     *
     * Get account external links.
     *
     */
    public function testGetAccountExternalLinks()
    {
    }

    /**
     * Test case for getMailboxList
     *
     * Get mailbox visible link list.
     *
     */
    public function testGetMailboxList()
    {
    }

    /**
     * Test case for updateExternalLink
     *
     * Update external link.
     *
     */
    public function testUpdateExternalLink()
    {
    }
}
