<?php
/**
 * NotificationControllerApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  DocStudio\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DocStudio Api Documentation
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: R125.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace DocStudio\Client\Test\Api;

use \DocStudio\Client\Configuration;
use \DocStudio\Client\ApiException;
use \DocStudio\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * NotificationControllerApiTest Class Doc Comment
 *
 * @category Class
 * @package  DocStudio\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NotificationControllerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAccountPreferences
     *
     * Get account related notification preferences.
     *
     */
    public function testGetAccountPreferences()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCorporateUserAccountPreferences
     *
     * Get corporate user account related notification preferences.
     *
     */
    public function testGetCorporateUserAccountPreferences()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMailboxPreferences
     *
     * Get corporate user mailbox related notification preferences.
     *
     */
    public function testGetMailboxPreferences()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMailboxPreferences1
     *
     * Get mailbox related notification preferences.
     *
     */
    public function testGetMailboxPreferences1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUnreadNotifications
     *
     * Get unread notifications.
     *
     */
    public function testGetUnreadNotifications()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for markAllNotificationRead
     *
     * Mark notifications as read.
     *
     */
    public function testMarkAllNotificationRead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for markNotificationRead
     *
     * Mark notifications as read.
     *
     */
    public function testMarkNotificationRead()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for saveAccountPreferences
     *
     * Update account related notification preferences.
     *
     */
    public function testSaveAccountPreferences()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for saveMailboxPreferences
     *
     * Update mailbox related notification preferences.
     *
     */
    public function testSaveMailboxPreferences()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setCorporateUserAccountPreferences
     *
     * Update corporate user account related notification preferences.
     *
     */
    public function testSetCorporateUserAccountPreferences()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setMailboxPreferences
     *
     * Update corporate user mailbox related notification preferences.
     *
     */
    public function testSetMailboxPreferences()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
